### ISSUE TITLE
File Names with GitHub Actions

### ISSUE THREAD

**Issue by TimothyLuke** [BigWigsMods/packager#100]
Hi All and @p3lim

I am trying to migrate from Travis-CI.org to GitHub Actions.  I have it building and behaving but the file names of the artifacts seem to be different to what I am expecting.

On a check-in I used to get an alpha with `{lastTag}-{nocommits}-g{comitid}-{gameversion}.zip` instead I am getting `{comitid}-{gameversion}.zip`  

![image](https://user-images.githubusercontent.com/573717/120580099-bd356200-c467-11eb-8f73-d951279b382b.png)

my config is: 
```
      # Runs a set of commands using the runners shell
      - name: Create Package Classic
        uses: BigWigsMods/packager@master
        if: ${{ github.event_name != 'pull_request' }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        with:
          args: -g classic -m .pkgmeta -w 25155
```
