### ISSUE TITLE
Using $GITHUB_OUTPUT as changelog

### ISSUE THREAD

**Issue by BreakBB** [BigWigsMods/packager#151]
I am wondering if it is possible to generate a changelog in a seperate action step, pipe it to $GITHUB_OUTPUT and use that as a manual changelog.

I can't find a reference in the [release.sh Usage](https://github.com/BigWigsMods/packager#usage), but some flag to add the path to the output would be great. Something like this:

```yml
    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Generate Changelog
        id: changelog
        run: python changelog.py >> $GITHUB_OUTPUT

      - name: Package and release Wrath
        uses: BigWigsMods/packager@master
        with:
          args: -e -l -m .pkgmeta.yaml -x ${{steps.changelog.outputs.*}}
```

**Comment by BreakBB** [comment]
Nevermind, my idea was way too complicated. It is easier to just pipe the output of the changelog script to a file and reference that file in the next step.

```yml
    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Generate Changelog
        id: changelog
        run: |
          python changelog.py -p >> CHANGELOG.md

      - name: Package and release Wrath
        uses: BigWigsMods/packager@master
        with:
          args: -d -e -l -m .pkgmeta.yaml
```

Together with this in the `.pkgmeta.yaml`:

```yml
manual-changelog:
  filename: CHANGELOG.md
  markup-type: markdown
```
