### ISSUE TITLE
Failed workflow, uploaded files

### ISSUE THREAD

**Issue by lukzmu** [BigWigsMods/packager#171]
Hello there.

I am currently having an issue with the packager that gives me a false positive:
- The files are correctly uploaded to CurseForge,
- The release has all the commits in description that were added in new version,
- I am getting a failed workflow.

Error that I am getting:

```
Updating GitHub release: https://github.com/lukzmu/notifly/releases/tag/1.0.12
Error! (403)
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/releases/releases#update-a-release",
  "status": "403"
}

Packaging complete.
```

This is the code I have for my release workflow:

```
release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets entire git history, needed for automatic changelogs
      - name: Package and release
        uses: BigWigsMods/packager@v2
```

I also have the `CF_API_KEY` set in workflow action secrets.

Thank you in advance!
