### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by p3lim** [BigWigsMods/packager#18]
Would you be opposed to keeping a Dockerfile in this repo and setting up automatic updates for an "official" Docker image?
This would simplify (and speed up) running the packager on CIs using Docker like CircleCI.

I could create the Dockerfile (and even provide a sample config for CircleCI) and help set up the automation with Docker Hub for the image (I could also manage this, but that would require collaboration access to the repo).

I've got this set up locally already, but it'll require manually updating the Docker image every time the script changes, which is what I'm trying to get rid of.

**Comment by nebularg** [comment]
Go for it 😄

**Comment by p3lim** [comment]
Just waiting for approval on the link to Docker Hub, I guess you got the mail.

**Comment by p3lim** [comment]
https://hub.docker.com/r/p3lim/wow-packager/

Gonna make sure I get CircleCI right and I'll paste a sample config for that too.

**Comment by p3lim** [comment]
CircleCI config to run release.sh on tags, using the Docker image:
```yaml
version: 2
jobs:
  release:
    docker:
      - image: p3lim/wow-packager:latest
    steps:
      - checkout
      - run: release.sh
workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
```

Full docs on this: https://circleci.com/docs/2.0/#adding-a-yml-file
