### ISSUE TITLE
SVN tag URLs in pkgmeta require different syntax then CF packager

### ISSUE THREAD

**Issue by Nevcairiel** [BigWigsMods/packager#21]
SVN tag URLs require a different syntax in the CF packager and in this script.

CurseForge compatible:
```
externals:
  LibStub: https://repos.wowace.com/wow/libstub/tags/1.0
```

release.sh compatible:
```
externals:
  LibStub:
    url: https://repos.wowace.com/wow/libstub/trunk/
    tag: 1.0
```

Neither option works on both. The first one has release.sh attempt to access the repo as Git, and the second has CurseForge pull in trunk instead of the tag.

Can we get the first variant supported by release.sh, so that the same syntax can be used on both?
Ideally it could perhaps attempt to probe the URL for the repo type, instead of guessing from the URL structure.
