### ISSUE TITLE
Release.sh not uploading release file to github

### ISSUE THREAD

**Issue by mjbrowns** [BigWigsMods/packager#56]
I'm very new to this, and for the moment I just want to have the release packaged up to github where my source is.   I'm trying to use CurseBreaker to manage my mods.  I've configured my github actions using the template provided to do release automation.  I don't see any errors in the flow that results but it doesn't seem like the file is being updated to github.  I'm sure I'm missing something simple but I just can't figure this out.

my mod is here: https://github.com/mjbrowns/SoundMapper

**Comment by Solor** [comment]
@mjbrowns  use this to create github release
```
name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: release.sh
```

**Comment by mjbrowns** [comment]
Well, I was.  However, I figured it out (mostly).

The doc says to use secrets.GITHUB_OAUTH so I had attempted to use exactly that naming convention, but github won't permit secrets to have the prefix GITHUB_*  so I assumed the GITHUB_ was automatic.  Thus my secret was coming through blank.  I renamed the variable to just OAUTH in the workflow and it worked.  

It might be helpful to update the doc accordingly to use a valid secret prefix.

Now I just have to figure out the wowinterface bit...

**Comment by Solor** [comment]
No need to generate secrets token, just use `${{ secrets.GITHUB_TOKEN }}`

**Comment by nebularg** [comment]
I updated the action wiki page to use `GITHUB_TOKEN` and noted the naming restriction for your own PAT

**Comment by nebularg** [comment]
Also to make sure changelogs are generated correctly, you should modify the clone step to be

```yaml
      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
```
otherwise the action is overzealous about pruning extra data, which apparently includes tags
