### ISSUE TITLE
Commented out externals are still checked out

### ISSUE THREAD

**Issue by Tuller** [BigWigsMods/packager#66]
If you comment out an external library within a pkgmeta file and then run the deploy script, it'll will still be checked out. In this case it will be pulled into # libs as the folder.

```yml
package-as: ExampleAddon

externals:
  # libs/AceAddon-3.0: https://repos.wowace.com/wow/ace3/trunk/AceAddon-3.0
```

As a workaround you can just delete the line.
