### ISSUE TITLE
Option to skip uploading changelog

### ISSUE THREAD

**Issue by p3lim** [BigWigsMods/packager#71]
I specifically need this for GitHub releases, but for all three would be good too.

**Comment by kemayo** [comment]
As a workaround, I [wound up](https://github.com/kemayo/wow-silverdragon/blob/master/.github/workflows/package.yml) building a manual changelog and then using a tool to slice out just the current release's changes to use as the packager-changelog. This gets me decent GitHub release notes... at the cost of overwriting my WoWI changelog with only the current release. So, yeah, it's not perfect.

**Comment by p3lim** [comment]
I make my own changelogs in markdown format, ended up just trimming the changelog down to the first header and paragraph(s).
```yaml
- name: Trim changelog
  run: sed -ni '1p;2,/^###/{/^###/q;p;}' CHANGELOG.md
```
If you want to close the issue that's fine by me, I'm satisfied with this.

**Comment by teelolws** [comment]
Actually I'd like this, an option to not include the changelog.md in the file. I still like the changelog it writes for the description fields, though.

**Comment by nanderson11** [comment]
I was looking for a way to have a manual changelog and only include the latest version's changes in the Github release and Curseforge release. The Github Action that @kemayo made, `kemayo/actions-recent-changelog`, worked great for this. I added one extra step, having the packager ignore the temporary changelog made. For quick reference, I added the code below to the respective files:

Packager Workflow YAML (before the packager step)
```
- uses: kemayo/actions-recent-changelog@v1
        with:
          input: CHANGELOG.md
          output: RECENT_CHANGES.md
```

.pkgmeta
```
manual-changelog:
  filename: RECENT_CHANGES.md
  markup-type: markdown

ignore:
  - RECENT_CHANGES.md
```

I would definitely like it if having a manual changelog and only including the latest version's changes was a part of the packager though. I'm not sure if that should be a separate issue though, since it's not the same thing as the title of this issue, even though this solution was discussed here.
