### ISSUE TITLE
Feature Request: Allow targetting game type in .pkgmeta.

### ISSUE THREAD

**Issue by StormFX** [BigWigsMods/packager#92]
This could be something that' been mentioned before, but it would be nice if we could specify a game type in the .pkgmeta for certain fields. Eg:

```yaml
externals:
  Libs/LibDualSpec-1.0: 
    url: https://repos.wowace.com/wow/libdualspec-1-0
    tag: latest
    game-type: retail
```

This may help alleviate the need for multiple .pkgmeta files. I'm not sure how multiple game types would be handled, (ie, comma-delimited list or multiple entries).
